GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTc4Njc2NzA5fQ.LCI1ZNQcw0M1hHQo9wZgRe0Jy73OpRNMDm8OJvS_LyY

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTc4NjcxMjkyfQ.JSxk2W3Zj6sqV-gZJrVJgUwba6aNUqZ6eg_os3Vx2Hs"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}