GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTc4OTA4NTU2LCJleHAiOjE1Nzg5MDg1ODZ9.uD3T4MqE50RDkxninlHG-I7XiceM3t0vAzAvnuwt1--N_SePVKGNG7tmOADCMF5g95bzR1U5g8wjuIq7EjmEwPk96mEDz-hviu4_0fATX2vPDw6MrJ3asZJqbcTm0tPE_6pWHUKA8Siys53VdE3OLKOOKw7axcP4DfQT92iXSKg

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTc4OTA4NTU2fQ.m2HrfdOJn3CB463LKE2ZSEHjda0MLDpvH8VDEGreMaI"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}